### ISSUE TITLE
Traffic Light Man

### ISSUE THREAD

**Issue by CreatingCalifornia** [Gamearoo-s-Development/Realistic-Traffic-Control#6]
Add the ability to add any type of traffic light onto your head
![IMG_3023](https://github.com/Gamearoo-s-Development/Realistic-Traffic-Control/assets/156473479/adab74ce-c0df-414c-8d94-af4f1b6622d7)
![IMG_3024](https://github.com/Gamearoo-s-Development/Realistic-Traffic-Control/assets/156473479/e43cb4b5-64eb-4fe7-aaf0-66be3c30468a)

**Comment by GamearooCodes** [comment]
this is sadly not possible due to how the traffic frames code is handled it will just not look the same when on the head
