### ISSUE TITLE
Red, Red & Yellow/Amber then Green or allow sensors and pedestrian buttons to fire events that OC can listen for

### ISSUE THREAD

**Issue by lexi-o99** [Gamearoo-s-Development/Realistic-Traffic-Control#9]
**Is your feature request related to a problem? Please describe.**
I'm from the UK and when our traffic lights are going to green we have red, red & yellow/amber and then green. Also for crossings when the crossing lights flash as well as the traffic light controlling the crossing for the cars we have the "green man" flashing and the yellow/amber light flashing.

**Describe the solution you'd like**
It'd be nice if there was a toggle on the traffic light control box to use "UK" style as describer above and/or have sensors & pedestrian crossing buttons fire an event that OpenComputers can listen for

**Describe alternatives you've considered**
I am writing a script that uses OC for managing a simple crossing so I can have the UK style lights but  I don't want to have to cycle the pedestrian crossings every time as there might not be anyone waiting to cross.

**Additional context**
The full sequence for UK traffic lights are as follows. Red > Red & Yellow/Amber (both lit at the same time) > Green > Amber > Red. Also if someone presses the crossing button the traffic lights cycle to red, then the pedestrian lights cycle to green (or in this case white). After the crossing waiting time is up the green (white) light flashes (to warn pedestrians that the light is about to change) and the traffic light goes from red to flashing yellow/amber for a few seconds (this means proceed if clear and wait if not) then at the same time the pedestrian light goes red and the traffic light goes green.

**Comment by GamearooCodes** [comment]
Hello srry but this mod is USA based and has no plans on making stuff if your talking about phases there is OC support you can use

**Comment by lexi-o99** [comment]
That's fair enough that yu are not going to natively support UK style. I am doing a custom OC integration anyway. Do the under road sensors or pedestrian buttons fire OC event's when pressed? I've checked upstream docks but it doesn't mention anything like that. If not can that be the suggestion instead, to make it so sensors and pedestrian buttons fire events that we can listen out for in OC code?

**Comment by GamearooCodes** [comment]
No sadly not however u could use preser plates and Redstone with the Redstone module yo make sensors

**Comment by lexi-o99** [comment]
I was hoping to use the under road sensors and pedestrian crossing buttons as they are very sleek.

I might fork the repo and take a crack at making the sensors and buttons fire events. If I do would you like me to submit a PR or is this not something you'd want in your version?

**Comment by GamearooCodes** [comment]
you are more than welcome to make PR's rather it gets accepted or not is another question
